---
- hosts: websever
  become: yes
  vars:
    build_number: '{{ BUILD_NUMBER }}'
    ms: '{{ ms }}'
  tasks:
      
    - name: login to jfrog
      shell: docker login -u snadim777@gmail.com -p Devops@123 https://devops392.jfrog.io/  
    
    - name: pull an image
      shell: docker pull devops392.jfrog.io/docker-cicd-docker-local/app-a/login:{{ build_number }}

    - name: remove container
      shell: docker rm -f devopsAppDeploy
        
    - name: create a application container
      shell: docker run -id --name devopsAppDeploy -p 8111:8080 devops392.jfrog.io/docker-cicd-docker-local/app-a/login:{{ build_number }}
   
